version: '3.8'

services:
  purchase-api:
    build:
      context: .
      dockerfile: Dockerfile.hw6
    container_name: purchase-api
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoints:/app/checkpoints
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - local-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - local-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=Europe/Moscow
    depends_on:
      - prometheus
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: