FROM python:3.9-slim

WORKDIR /app

# Копируем requirements.txt первым для кэширования слоя
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы проекта
COPY . .

# Команда для запуска приложения
CMD ["uvicorn", "app.hw6.app:create_app", "--host", "0.0.0.0", "--port", "8000"]